import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from './ui/sideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-start h-screen bg-background`}>
        <div className=' min-w-[300px]'>
          <SideNav/>
        </div>
        
        <div className='flex justify-center items-center w-full h-full'>
          {children}
        </div>  
      </body>
    </html>
  )
}
